### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by Adam-SungMin-Park** [Adam-SungMin-Park/driving-game#2]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List
- [x] create index.html
- [x] create styles.css and link it to index.html
- [x] structure the HTML and style it using CSS
- [x] add an image of the car into HTML 
- [x] style the car using CSS 
- [x] position the car on the upper left hand side of the corner
