### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by Adam-SungMin-Park** [Adam-SungMin-Park/driving-game#3]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List
- [x] link main.js to index.html
- [x] Listen for 'keydown' events on the document.
- [x] image rotates when user presses on arrow keys
- [x] turn 90 degree to left and right 
- [x] smooth turning
