### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by Adam-SungMin-Park** [Adam-SungMin-Park/driving-game#4]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Add a location to your data model to hold the car's x and y coordinates on the page.
- [x] Use absolute positioning for your image.
- [x] Use the style property of element objects to change your car's top and left box offset styles.
- [x] Move your car every 16 milliseconds for a smooth movement.
