### ISSUE TITLE
User can steer their car

### ISSUE THREAD

**Issue by Adam-SungMin-Park** [Adam-SungMin-Park/driving-game#6]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] turning properly
- [x] up key = turns left from cars POV
- [x] down key = turns right from cars POV
- [x] left an right key go straight depending on the position of the car
